//! Regenerate `vectors/seeds.json`: for each seed Module, fixed seeds, their
//! written backups, and the keys they derive (FIPS 205 key-generation seeds,
//! public key, safety commitment), so that another device can check its
//! implementation of the derivation.
//!
//! `cargo run -p mor-airgap --example seed_vectors > modules/airgap/vectors/seeds.json`

use mor_airgap::seed::{Seed, SeedModule};
use mor_core::hash::tagged_hash_parts;

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn main() {
    let seeds: [[u8; 32]; 3] = [
        [0u8; 32],
        core::array::from_fn(|i| i as u8),
        mor_core::hash::sha256(b"MOR seed vector"),
    ];
    let mut out = vec![];
    for module in SeedModule::ALL {
        let tag = match module {
            SeedModule::Words => mor_airgap::seed::tag::WORDS_KEY,
            SeedModule::Hex => mor_airgap::seed::tag::HEX_KEY,
        };
        for e in &seeds {
            let s = Seed::new(module, *e);
            let mut keys = vec![];
            for (scheme, index) in [(2u8, 0u64), (2, 1), (3, 0), (2, 1000)] {
                let i = index.to_be_bytes();
                let a = tagged_hash_parts(tag, &[e, &[scheme], &i, &[0]]);
                let b = tagged_hash_parts(tag, &[e, &[scheme], &i, &[1]]);
                let k = s.key(scheme, index);
                keys.push(format!(
                    "        {{\"scheme\": {scheme}, \"index\": {index}, \"sk_seed\": \"{}\", \"sk_prf\": \"{}\", \"pk_seed\": \"{}\", \"public_key\": \"{}\", \"commitment\": \"{}\"}}",
                    hex(&a[..16]),
                    hex(&a[16..]),
                    hex(&b[..16]),
                    hex(&k.public()),
                    hex(&k.commitment())
                ));
            }
            out.push(format!(
                "    {{\n      \"module\": \"{}\",\n      \"seed\": \"{}\",\n      \"backup\": \"{}\",\n      \"keys\": [\n{}\n      ]\n    }}",
                module.name(),
                hex(e),
                s.backup(),
                keys.join(",\n")
            ));
        }
    }
    println!(
        "{{\n  \"description\": \"Seed Modules words and hex, draft 1: backups and derived safety keys. Generated by `cargo run -p mor-airgap --example seed_vectors`.\",\n  \"vectors\": [\n{}\n  ]\n}}",
        out.join(",\n")
    );
}
